# Generated by Django 3.1.2 on 2020-10-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('temperature', models.FloatField()),
                ('mtco2', models.FloatField()),
                ('status', models.CharField(choices=[('Good', 'good'), ('Medium', 'medium'), ('Danger', 'danger')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('temperature', models.FloatField()),
                ('mtco2', models.FloatField()),
                ('status', models.CharField(choices=[('Good', 'good'), ('Medium', 'medium'), ('Danger', 'danger')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.continent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('temperature', models.FloatField()),
                ('mtco2', models.FloatField()),
                ('status', models.CharField(choices=[('Good', 'good'), ('Medium', 'medium'), ('Danger', 'danger')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
